# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - node_modules

test:
  script:
    - apk --no-cache add npm
    - npm install
    - npm run production
    - hugo
  except:
    - master

pages:
  script:
    - apk --no-cache add npm
    - npm install
    - npm run production
    - hugo
  artifacts:
    paths:
      - public
  only:
    - master
